### ISSUE TITLE
hotelCreateDB.sql中新建的几个表名称跟后面关联的sql语句表名大小写不一致，导致执行出错

### ISSUE THREAD

**Issue by lgs3137** [chironyf/HotelManagementSystem#1]
hotelCreateDB.sql中新建的几个表名称跟后面执行关联sql语句中表名大小写不一致，导致执行出错

**Comment by chironyf** [comment]
具体哪里执行错了?

**Comment by lgs3137** [comment]
我发现java代码里面的所有sql语句的表名都是用小写的。。。
hotelCreateDB.sql里面建表语句
CREATE TABLE systemAdministrator,VIPLevel,roomTypeAndPrice,orderTracking,timeExtension
这些又是有大写的

**Comment by chironyf** [comment]
MySQL默认不区分大小写

**Comment by lgs3137** [comment]
额。。。好吧，我的MySQL开了区分大小写

**Comment by lgs3137** [comment]
我自己改下吧
