### ISSUE TITLE
请问这个数据集怎么找的啊

### ISSUE THREAD

**Issue by Spongesquarhead** [chironyf/HotelManagementSystem#4]

**Comment by lianglinyuan** [comment]
代码随机生成的假数据


------------------ 原始邮件 ------------------
发件人: Spongesquarhead <notifications@github.com&gt;
发送时间: 2020年7月12日 20:40
收件人: chironyf/hotel-management-system <hotel-management-system@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[chironyf/hotel-management-system] 请问这个数据集怎么找的啊 (#4)





 
Closed #4.
